### ISSUE TITLE
Error in Ubuntu

### ISSUE THREAD

**Issue by abrahamsurf** [dingtoffee/YAHP#2]
Used your config files but getting this error; 

Aug 14 23:18:02 osboxes supervisord[8627]: 2021-08-14 23:18:02,040 WARN For [program:rdpy], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
Aug 14 23:18:02 osboxes supervisord[8627]: 2021-08-14 23:18:02,040 INFO Included extra file "/etc/supervisor/conf.d/rdpy.conf" during parsing
Aug 14 23:18:02 osboxes supervisord[8627]: 2021-08-14 23:18:02,044 INFO RPC interface 'supervisor' initialized
Aug 14 23:18:02 osboxes supervisord[8627]: 2021-08-14 23:18:02,044 CRIT Server 'unix_http_server' running without any HTTP authentication checking
Aug 14 23:18:02 osboxes supervisord[8627]: 2021-08-14 23:18:02,045 INFO supervisord started with pid 8627
Aug 14 23:18:03 osboxes supervisord[8627]: 2021-08-14 23:18:03,049 INFO spawned: 'rdpy' with pid 8635
Aug 14 23:18:03 osboxes supervisord[8627]: 2021-08-14 23:18:03,062 INFO exited: rdpy (exit status 2; not expected)
Aug 14 23:18:04 osboxes supervisord[8627]: 2021-08-14 23:18:04,064 INFO spawned: 'rdpy' with pid 8638
Aug 14 23:18:04 osboxes supervisord[8627]: 2021-08-14 23:18:04,077 INFO exited: rdpy (exit status 2; not expected)
Aug 14 23:18:06 osboxes supervisord[8627]: 2021-08-14 23:18:06,081 INFO spawned: 'rdpy' with pid 8639
Aug 14 23:18:06 osboxes supervisord[8627]: 2021-08-14 23:18:06,096 INFO exited: rdpy (exit status 2; not expected)
Aug 14 23:18:09 osboxes supervisord[8627]: 2021-08-14 23:18:09,103 INFO spawned: 'rdpy' with pid 8640
Aug 14 23:18:09 osboxes supervisord[8627]: 2021-08-14 23:18:09,125 INFO exited: rdpy (exit status 2; not expected)
Aug 14 23:18:10 osboxes supervisord[8627]: 2021-08-14 23:18:10,127 INFO gave up: rdpy entered FATAL state, too many start retries too quickly

**Comment by iamhunggy** [comment]
Hi, 
It looks like the supervisor is not able to start the rdpy script correctly. Have you experienced any problems by running the rdpy.py script alone? I was not able to replicate your problem as I could run the script without any errors. 

Another thing worth trying would be removing "redirect_stderr=true" and change "autorestart=false" from the configuration file rdpy.conf to see if the problem still continue? Make sure you stopped the supervisor process  and  kill the running process that are holding the 3389 port first before you try to modify the configuration file and restart the service.

**Comment by iamhunggy** [comment]
Closing this issue as there's no further updates.
